replicaCount: 2

image:
  repository: 907260787494.dkr.ecr.us-east-1.amazonaws.com/camp
  tag: latest
  pullPolicy: Always

container:
  name: yelpcamp
  port: 3000

strategy:
  type: RollingUpdate

service:
  name: yelp-camp-service
  type: ClusterIP
  port: 3000
  targetPort: 3000

resources:
  requests:
    cpu: "150m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

labels:
  app: yelp-camp

# ✅ ADD THIS BLOCK
ingress:
  enabled: true
  className: nginx
  paths:
    - path: /
      pathType: Prefix

hpa:
 enabled: true
 minReplicas: 2
 maxReplicas: 5
 cpuUtilization: 50

secretName: yelp-camp-secrets

secrets:
  CLOUDINARY_CLOUD_NAME: duqpuevli
  CLOUDINARY_KEY: 848447446372297
  CLOUDINARY_SECRET: KfJS47IfT4VA5UHDlbqFJbwaN_Y
  MAPBOX_TOKEN: sk.eyJ1IjoidmlzaHdhamVldGtvcmUiLCJhIjoiY21weWQwN2doMDVoMTJzcXkwMDIwZGdsYSJ9.KgEY2FuCuhJiqSY5RAsVkA
  DB_URL: "mongodb+srv://vishwajitkore2001_db_user:admin%40123@devopsdb.xs7o8ug.mongodb.net/?appName=devopsdb"
  NAME: devopsdb
  SECRET: devopsguru

