apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.labels.app }}-deployment

spec:
  replicas: {{ .Values.replicaCount }}

  strategy:
    type: {{ .Values.strategy.type }}

  selector:
    matchLabels:
      app: {{ .Values.labels.app }}

  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}

    spec:
      containers:
        - name: {{ .Values.container.name }}-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.container.port }}

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}

          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: CLOUDINARY_CLOUD_NAME

            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: CLOUDINARY_KEY

            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: CLOUDINARY_SECRET

            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: MAPBOX_TOKEN

            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: DB_URL

            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: SECRET

          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.container.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.container.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
