apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
stringData:
  CLOUDINARY_CLOUD_NAME: {{ .Values.secrets.CLOUDINARY_CLOUD_NAME | b64enc }}
  CLOUDINARY_KEY: {{ .Values.secrets.CLOUDINARY_KEY | b64enc }}
  CLOUDINARY_SECRET: {{ .Values.secrets.CLOUDINARY_SECRET | b64enc }}
  MAPBOX_TOKEN: {{ .Values.secrets.MAPBOX_TOKEN | b64enc }}
  DB_URL: {{ .Values.secrets.DB_URL | b64enc }}
  SECRET: {{ .Values.secrets.SECRET | b64enc }}
