apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
stringData:
  CLOUDINARY_CLOUD_NAME: "{{ .Values.secrets.CLOUDINARY_CLOUD_NAME }}"
  CLOUDINARY_KEY: "{{ .Values.secrets.CLOUDINARY_KEY }}"
  CLOUDINARY_SECRET: "{{ .Values.secrets.CLOUDINARY_SECRET }}"
  MAPBOX_TOKEN: "{{ .Values.secrets.MAPBOX_TOKEN }}"
  DB_URL: "{{ .Values.secrets.DB_URL }}"
  NAME: "{{ .Values.secrets.NAME }}"
  SECRET: "{{ .Values.secrets.SECRET }}"
